syntax enable
set background=light
colorscheme solarized
set visualbell
set noerrorbells
set number
set nocompatible
set showmode
set showcmd
set mouse=a
set t_Co=256
set autoindent
set tabstop=2
set shiftwidth=4
set expandtab
set softtabstop=2
set relativenumber
set cursorline
set wrap
set linebreak
set wrapmargin=2
set scrolloff=5
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoread
set listchars=tab:»·,trail:·
set list
set wildmenu
set wildmode=longest:list,full
set number
